groups:
- name: Traffic
  rules:
    - record: http_request_duration_seconds_total:sum_irate
      expr: sum(irate(http_request_duration_seconds_count[1m])) by (method, handler)


- name: Errors
  rules:
    - record: http_request_duration_seconds_error:sum_irate
      expr: sum(irate(http_request_duration_seconds_count{status=~"2[d]{2}"}[1m])) by (method, handler)

    - record:  http_request_duration_seconds_error_rate
      expr:
        http_request_duration_seconds_error:sum_irate
        /
        http_request_duration_seconds_total:sum_irate


- name: Latency
  rules:
    - record: http_request_duration_seconds_sum:sum_irate
      expr: sum(irate(http_request_duration_seconds_sum[1m])) by (method, handler)

    - record:  http_request_duration_seconds_latencia_media
      expr:
        http_request_duration_seconds_sum:sum_irate
        /
        http_request_duration_seconds_total:sum_irate
